default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= ENV.fetch("DATABASE_USER", "ritchermap") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "ritchermap") %>

development:
  <<: *default
  database: ritchermap_accounts_development

test:
  <<: *default
  database: ritchermap_accounts_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "ritchermap_accounts") %>
  url: <%= ENV["DATABASE_URL"] %>
