source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/richiexuetang/ritcher-map.git" }

ruby '3.2.0'

gem 'rails', '~> 7.1.0'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.0'
gem 'redis', '~> 5.0'

# API & Serialization
gem 'jsonapi-serializer', '~> 2.2'
gem 'rack-cors'
gem 'rack-attack'

# Authentication & Authorization
gem 'jwt'
gem 'bcrypt'

# File Processing
gem 'image_processing', '~> 1.12'
gem 'aws-sdk-s3', '~> 1.140'
gem 'shrine', '~> 3.5'
gem 'marcel', '~> 1.0'

# Background Jobs
gem 'sidekiq', '~> 7.2'
gem 'sidekiq-cron', '~> 1.12'

# Caching
gem 'redis-rails'
gem 'dalli'

# Monitoring
gem 'sentry-ruby'
gem 'sentry-rails'
gem 'newrelic_rpm'

# Utilities
gem 'bootsnap', '>= 1.4.4', require: false
gem 'kaminari'
gem 'paper_trail'
gem 'friendly_id', '~> 5.5'
gem 'acts-as-taggable-on', '~> 10.0'
gem 'globalize', '~> 6.3'
gem 'aasm'

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'rubocop-rails'
end

group :test do
  gem 'shoulda-matchers'
  gem 'webmock'
  gem 'vcr'
  gem 'database_cleaner-active_record'
  gem 'simplecov'
end