[server]
host = "127.0.0.1"
port = 8080
workers = 2
max_connections = 100
timeout_seconds = 30

[database]
url = "postgresql://postgres:postgres@localhost:5432/ritcher_tiles"
max_connections = 10
min_connections = 5
acquire_timeout_seconds = 30
idle_timeout_seconds = 300

[redis]
url = "redis://localhost:6379"
pool_size = 10
timeout_seconds = 5
ttl_seconds = 3600

[tile]
tile_size = 256
max_zoom = 18
min_zoom = 0
formats = ["png", "jpg", "webp"]
compression_quality = 85

[tile.cache_headers]
max_age = 3600
stale_while_revalidate = 86400

[storage]
base_path = "./tiles"
temp_path = "./tmp"
cdn_base_url = "https://cdn.ritcher.dev"

[metrics]
enabled = true
endpoint = "/metrics"