[server]
host = "0.0.0.0"
port = 8080
workers = 8
max_connections = 1000
timeout_seconds = 30

[database]
url = "postgresql://user:pass@postgres:5432/ritcher_tiles"
max_connections = 50
min_connections = 10
acquire_timeout_seconds = 30
idle_timeout_seconds = 600

[redis]
url = "redis://redis:6379"
pool_size = 50
timeout_seconds = 10
ttl_seconds = 7200

[tile]
tile_size = 256
max_zoom = 18
min_zoom = 0
formats = ["png", "jpg", "webp"]
compression_quality = 80

[tile.cache_headers]
max_age = 7200
stale_while_revalidate = 86400

[storage]
base_path = "/app/tiles"
temp_path = "/tmp"
cdn_base_url = "https://cdn.ritcher.dev"

[metrics]
enabled = true
endpoint = "/metrics"