// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.26.1
// source: internal/proto/events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_UNKNOWN MessageType = 0
	// Connection events
	MessageType_CONNECTION_ESTABLISHED MessageType = 1
	MessageType_CONNECTION_CLOSED      MessageType = 2
	// Marker events
	MessageType_MARKER_CREATED     MessageType = 10
	MessageType_MARKER_UPDATED     MessageType = 11
	MessageType_MARKER_DELETED     MessageType = 12
	MessageType_MARKER_BULK_UPDATE MessageType = 13
	// Presence events
	MessageType_USER_JOINED          MessageType = 20
	MessageType_USER_LEFT            MessageType = 21
	MessageType_USER_LOCATION_UPDATE MessageType = 22
	MessageType_USER_STATUS_UPDATE   MessageType = 23
	// Collaboration events
	MessageType_COLLABORATION_SYNC      MessageType = 30
	MessageType_COLLABORATION_CURSOR    MessageType = 31
	MessageType_COLLABORATION_SELECTION MessageType = 32
	// System events
	MessageType_PING  MessageType = 90
	MessageType_PONG  MessageType = 91
	MessageType_ERROR MessageType = 99
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "CONNECTION_ESTABLISHED",
		2:  "CONNECTION_CLOSED",
		10: "MARKER_CREATED",
		11: "MARKER_UPDATED",
		12: "MARKER_DELETED",
		13: "MARKER_BULK_UPDATE",
		20: "USER_JOINED",
		21: "USER_LEFT",
		22: "USER_LOCATION_UPDATE",
		23: "USER_STATUS_UPDATE",
		30: "COLLABORATION_SYNC",
		31: "COLLABORATION_CURSOR",
		32: "COLLABORATION_SELECTION",
		90: "PING",
		91: "PONG",
		99: "ERROR",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":                 0,
		"CONNECTION_ESTABLISHED":  1,
		"CONNECTION_CLOSED":       2,
		"MARKER_CREATED":          10,
		"MARKER_UPDATED":          11,
		"MARKER_DELETED":          12,
		"MARKER_BULK_UPDATE":      13,
		"USER_JOINED":             20,
		"USER_LEFT":               21,
		"USER_LOCATION_UPDATE":    22,
		"USER_STATUS_UPDATE":      23,
		"COLLABORATION_SYNC":      30,
		"COLLABORATION_CURSOR":    31,
		"COLLABORATION_SELECTION": 32,
		"PING":                    90,
		"PONG":                    91,
		"ERROR":                   99,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_events_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_internal_proto_events_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_events_proto_rawDescGZIP(), []int{0}
}

type UserStatus int32

const (
	UserStatus_UNKNOWN_STATUS UserStatus = 0
	UserStatus_ONLINE         UserStatus = 1
	UserStatus_AWAY           UserStatus = 2
	UserStatus_BUSY           UserStatus = 3
	UserStatus_INVISIBLE      UserStatus = 4
	UserStatus_OFFLINE        UserStatus = 5
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "UNKNOWN_STATUS",
		1: "ONLINE",
		2: "AWAY",
		3: "BUSY",
		4: "INVISIBLE",
		5: "OFFLINE",
	}
	UserStatus_value = map[string]int32{
		"UNKNOWN_STATUS": 0,
		"ONLINE":         1,
		"AWAY":           2,
		"BUSY":           3,
		"INVISIBLE":      4,
		"OFFLINE":        5,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_events_proto_enumTypes[1].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_internal_proto_events_proto_enumTypes[1]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_events_proto_rawDescGZIP(), []int{1}
}

// Base message structure
type RealtimeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=realtime.MessageType" json:"type,omitempty"`
	GameId        string                 `protobuf:"bytes,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealtimeMessage) Reset() {
	*x = RealtimeMessage{}
	mi := &file_internal_proto_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeMessage) ProtoMessage() {}

func (x *RealtimeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeMessage.ProtoReflect.Descriptor instead.
func (*RealtimeMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_events_proto_rawDescGZIP(), []int{0}
}

func (x *RealtimeMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RealtimeMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN
}

func (x *RealtimeMessage) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *RealtimeMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RealtimeMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RealtimeMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RealtimeMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Position coordinates
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude      float64                `protobuf:"fixed64,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_internal_proto_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_internal_proto_events_proto_rawDescGZIP(), []int{1}
}

func (x *Position) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Position) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Position) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

// Marker events
type MarkerCreatedEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MarkerId        string                 `protobuf:"bytes,1,opt,name=marker_id,json=markerId,proto3" json:"marker_id,omitempty"`
	GameId          string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	CategoryId      string                 `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Position        *Position              `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Title           string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	VisibilityLevel int32                  `protobuf:"varint,8,opt,name=visibility_level,json=visibilityLevel,proto3" json:"visibility_level,omitempty"`
	CreatedBy       string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MarkerCreatedEvent) Reset() {
	*x = MarkerCreatedEvent{}
	mi := &file_internal_proto_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkerCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkerCreatedEvent) ProtoMessage() {}

func (x *MarkerCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkerCreatedEvent.ProtoReflect.Descriptor instead.
func (*MarkerCreatedEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_events_proto_rawDescGZIP(), []int{2}
}

func (x *MarkerCreatedEvent) GetMarkerId() string {
	if x != nil {
		return x.MarkerId
	}
	return ""
}

func (x *MarkerCreatedEvent) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *MarkerCreatedEvent) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *MarkerCreatedEvent) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *MarkerCreatedEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MarkerCreatedEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MarkerCreatedEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MarkerCreatedEvent) GetVisibilityLevel() int32 {
	if x != nil {
		return x.VisibilityLevel
	}
	return 0
}

func (x *MarkerCreatedEvent) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type MarkerUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarkerId      string                 `protobuf:"bytes,1,opt,name=marker_id,json=markerId,proto3" json:"marker_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	OldPosition   *Position              `protobuf:"bytes,3,opt,name=old_position,json=oldPosition,proto3" json:"old_position,omitempty"`
	NewPosition   *Position              `protobuf:"bytes,4,opt,name=new_position,json=newPosition,proto3" json:"new_position,omitempty"`
	OldTitle      string                 `protobuf:"bytes,5,opt,name=old_title,json=oldTitle,proto3" json:"old_title,omitempty"`
	NewTitle      string                 `protobuf:"bytes,6,opt,name=new_title,json=newTitle,proto3" json:"new_title,omitempty"`
	Changes       map[string]string      `protobuf:"bytes,7,rep,name=changes,proto3" json:"changes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdatedBy     string                 `protobuf:"bytes,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Version       int32                  `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkerUpdatedEvent) Reset() {
	*x = MarkerUpdatedEvent{}
	mi := &file_internal_proto_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkerUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkerUpdatedEvent) ProtoMessage() {}

func (x *MarkerUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkerUpdatedEvent.ProtoReflect.Descriptor instead.
func (*MarkerUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_events_proto_rawDescGZIP(), []int{3}
}

func (x *MarkerUpdatedEvent) GetMarkerId() string {
	if x != nil {
		return x.MarkerId
	}
	return ""
}

func (x *MarkerUpdatedEvent) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *MarkerUpdatedEvent) GetOldPosition() *Position {
	if x != nil {
		return x.OldPosition
	}
	return nil
}

func (x *MarkerUpdatedEvent) GetNewPosition() *Position {
	if x != nil {
		return x.NewPosition
	}
	return nil
}

func (x *MarkerUpdatedEvent) GetOldTitle() string {
	if x != nil {
		return x.OldTitle
	}
	return ""
}

func (x *MarkerUpdatedEvent) GetNewTitle() string {
	if x != nil {
		return x.NewTitle
	}
	return ""
}

func (x *MarkerUpdatedEvent) GetChanges() map[string]string {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *MarkerUpdatedEvent) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *MarkerUpdatedEvent) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type MarkerDeletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarkerId      string                 `protobuf:"bytes,1,opt,name=marker_id,json=markerId,proto3" json:"marker_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	DeletedBy     string                 `protobuf:"bytes,3,opt,name=deleted_by,json=deletedBy,proto3" json:"deleted_by,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkerDeletedEvent) Reset() {
	*x = MarkerDeletedEvent{}
	mi := &file_internal_proto_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkerDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkerDeletedEvent) ProtoMessage() {}

func (x *MarkerDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkerDeletedEvent.ProtoReflect.Descriptor instead.
func (*MarkerDeletedEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_events_proto_rawDescGZIP(), []int{4}
}

func (x *MarkerDeletedEvent) GetMarkerId() string {
	if x != nil {
		return x.MarkerId
	}
	return ""
}

func (x *MarkerDeletedEvent) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *MarkerDeletedEvent) GetDeletedBy() string {
	if x != nil {
		return x.DeletedBy
	}
	return ""
}

func (x *MarkerDeletedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Presence events
type UserJoinedEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username        string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	GameId          string                 `protobuf:"bytes,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	InitialLocation *Position              `protobuf:"bytes,4,opt,name=initial_location,json=initialLocation,proto3" json:"initial_location,omitempty"`
	Status          UserStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=realtime.UserStatus" json:"status,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserJoinedEvent) Reset() {
	*x = UserJoinedEvent{}
	mi := &file_internal_proto_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserJoinedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserJoinedEvent) ProtoMessage() {}

func (x *UserJoinedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserJoinedEvent.ProtoReflect.Descriptor instead.
func (*UserJoinedEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_events_proto_rawDescGZIP(), []int{5}
}

func (x *UserJoinedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserJoinedEvent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserJoinedEvent) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *UserJoinedEvent) GetInitialLocation() *Position {
	if x != nil {
		return x.InitialLocation
	}
	return nil
}

func (x *UserJoinedEvent) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_UNKNOWN_STATUS
}

func (x *UserJoinedEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UserLeftEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLeftEvent) Reset() {
	*x = UserLeftEvent{}
	mi := &file_internal_proto_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLeftEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLeftEvent) ProtoMessage() {}

func (x *UserLeftEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLeftEvent.ProtoReflect.Descriptor instead.
func (*UserLeftEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_events_proto_rawDescGZIP(), []int{6}
}

func (x *UserLeftEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserLeftEvent) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *UserLeftEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UserLocationUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Position      *Position              `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Heading       float64                `protobuf:"fixed64,4,opt,name=heading,proto3" json:"heading,omitempty"`
	Speed         float64                `protobuf:"fixed64,5,opt,name=speed,proto3" json:"speed,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLocationUpdateEvent) Reset() {
	*x = UserLocationUpdateEvent{}
	mi := &file_internal_proto_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLocationUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLocationUpdateEvent) ProtoMessage() {}

func (x *UserLocationUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLocationUpdateEvent.ProtoReflect.Descriptor instead.
func (*UserLocationUpdateEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_events_proto_rawDescGZIP(), []int{7}
}

func (x *UserLocationUpdateEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserLocationUpdateEvent) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *UserLocationUpdateEvent) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *UserLocationUpdateEvent) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *UserLocationUpdateEvent) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *UserLocationUpdateEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type UserStatusUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Status        UserStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=realtime.UserStatus" json:"status,omitempty"`
	CustomStatus  string                 `protobuf:"bytes,4,opt,name=custom_status,json=customStatus,proto3" json:"custom_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatusUpdateEvent) Reset() {
	*x = UserStatusUpdateEvent{}
	mi := &file_internal_proto_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatusUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatusUpdateEvent) ProtoMessage() {}

func (x *UserStatusUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatusUpdateEvent.ProtoReflect.Descriptor instead.
func (*UserStatusUpdateEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_events_proto_rawDescGZIP(), []int{8}
}

func (x *UserStatusUpdateEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserStatusUpdateEvent) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *UserStatusUpdateEvent) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_UNKNOWN_STATUS
}

func (x *UserStatusUpdateEvent) GetCustomStatus() string {
	if x != nil {
		return x.CustomStatus
	}
	return ""
}

// Collaboration events
type CollaborationSyncEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // marker, guide, etc.
	ResourceId    string                 `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Operation     string                 `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"` // insert, delete, retain
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Revision      int64                  `protobuf:"varint,7,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollaborationSyncEvent) Reset() {
	*x = CollaborationSyncEvent{}
	mi := &file_internal_proto_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollaborationSyncEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollaborationSyncEvent) ProtoMessage() {}

func (x *CollaborationSyncEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollaborationSyncEvent.ProtoReflect.Descriptor instead.
func (*CollaborationSyncEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_events_proto_rawDescGZIP(), []int{9}
}

func (x *CollaborationSyncEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CollaborationSyncEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CollaborationSyncEvent) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *CollaborationSyncEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CollaborationSyncEvent) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *CollaborationSyncEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CollaborationSyncEvent) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type CollaborationCursorEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ResourceId     string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Position       int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	SelectionStart string                 `protobuf:"bytes,5,opt,name=selection_start,json=selectionStart,proto3" json:"selection_start,omitempty"`
	SelectionEnd   string                 `protobuf:"bytes,6,opt,name=selection_end,json=selectionEnd,proto3" json:"selection_end,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CollaborationCursorEvent) Reset() {
	*x = CollaborationCursorEvent{}
	mi := &file_internal_proto_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollaborationCursorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollaborationCursorEvent) ProtoMessage() {}

func (x *CollaborationCursorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollaborationCursorEvent.ProtoReflect.Descriptor instead.
func (*CollaborationCursorEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_events_proto_rawDescGZIP(), []int{10}
}

func (x *CollaborationCursorEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CollaborationCursorEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CollaborationCursorEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CollaborationCursorEvent) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *CollaborationCursorEvent) GetSelectionStart() string {
	if x != nil {
		return x.SelectionStart
	}
	return ""
}

func (x *CollaborationCursorEvent) GetSelectionEnd() string {
	if x != nil {
		return x.SelectionEnd
	}
	return ""
}

// System events
type PingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingEvent) Reset() {
	*x = PingEvent{}
	mi := &file_internal_proto_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingEvent) ProtoMessage() {}

func (x *PingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingEvent.ProtoReflect.Descriptor instead.
func (*PingEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_events_proto_rawDescGZIP(), []int{11}
}

func (x *PingEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type PongEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PingTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ping_timestamp,json=pingTimestamp,proto3" json:"ping_timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongEvent) Reset() {
	*x = PongEvent{}
	mi := &file_internal_proto_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongEvent) ProtoMessage() {}

func (x *PongEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongEvent.ProtoReflect.Descriptor instead.
func (*PongEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_events_proto_rawDescGZIP(), []int{12}
}

func (x *PongEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PongEvent) GetPingTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.PingTimestamp
	}
	return nil
}

type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	Recoverable   bool                   `protobuf:"varint,4,opt,name=recoverable,proto3" json:"recoverable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_internal_proto_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_events_proto_rawDescGZIP(), []int{13}
}

func (x *ErrorEvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorEvent) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *ErrorEvent) GetRecoverable() bool {
	if x != nil {
		return x.Recoverable
	}
	return false
}

// Connection info
type ConnectionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GameId        string                 `protobuf:"bytes,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	ConnectedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	ClientIp      string                 `protobuf:"bytes,5,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,6,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionInfo) Reset() {
	*x = ConnectionInfo{}
	mi := &file_internal_proto_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionInfo) ProtoMessage() {}

func (x *ConnectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionInfo.ProtoReflect.Descriptor instead.
func (*ConnectionInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_events_proto_rawDescGZIP(), []int{14}
}

func (x *ConnectionInfo) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ConnectionInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConnectionInfo) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ConnectionInfo) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

func (x *ConnectionInfo) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *ConnectionInfo) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *ConnectionInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Room info
type RoomInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomId          string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	GameId          string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	ConnectedUsers  []string               `protobuf:"bytes,3,rep,name=connected_users,json=connectedUsers,proto3" json:"connected_users,omitempty"`
	ConnectionCount int32                  `protobuf:"varint,4,opt,name=connection_count,json=connectionCount,proto3" json:"connection_count,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_internal_proto_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_events_proto_rawDescGZIP(), []int{15}
}

func (x *RoomInfo) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomInfo) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *RoomInfo) GetConnectedUsers() []string {
	if x != nil {
		return x.ConnectedUsers
	}
	return nil
}

func (x *RoomInfo) GetConnectionCount() int32 {
	if x != nil {
		return x.ConnectionCount
	}
	return 0
}

func (x *RoomInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RoomInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_internal_proto_events_proto protoreflect.FileDescriptor

const file_internal_proto_events_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/proto/events.proto\x12\brealtime\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x02\n" +
	"\x0fRealtimeMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.realtime.MessageTypeR\x04type\x12\x17\n" +
	"\agame_id\x18\x03 \x01(\tR\x06gameId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12C\n" +
	"\bmetadata\x18\a \x03(\v2'.realtime.RealtimeMessage.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\bPosition\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baltitude\x18\x03 \x01(\x01R\baltitude\"\xa2\x03\n" +
	"\x12MarkerCreatedEvent\x12\x1b\n" +
	"\tmarker_id\x18\x01 \x01(\tR\bmarkerId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\tR\n" +
	"categoryId\x12.\n" +
	"\bposition\x18\x04 \x01(\v2\x12.realtime.PositionR\bposition\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12F\n" +
	"\bmetadata\x18\a \x03(\v2*.realtime.MarkerCreatedEvent.MetadataEntryR\bmetadata\x12)\n" +
	"\x10visibility_level\x18\b \x01(\x05R\x0fvisibilityLevel\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x03\n" +
	"\x12MarkerUpdatedEvent\x12\x1b\n" +
	"\tmarker_id\x18\x01 \x01(\tR\bmarkerId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x125\n" +
	"\fold_position\x18\x03 \x01(\v2\x12.realtime.PositionR\voldPosition\x125\n" +
	"\fnew_position\x18\x04 \x01(\v2\x12.realtime.PositionR\vnewPosition\x12\x1b\n" +
	"\told_title\x18\x05 \x01(\tR\boldTitle\x12\x1b\n" +
	"\tnew_title\x18\x06 \x01(\tR\bnewTitle\x12C\n" +
	"\achanges\x18\a \x03(\v2).realtime.MarkerUpdatedEvent.ChangesEntryR\achanges\x12\x1d\n" +
	"\n" +
	"updated_by\x18\b \x01(\tR\tupdatedBy\x12\x18\n" +
	"\aversion\x18\t \x01(\x05R\aversion\x1a:\n" +
	"\fChangesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x01\n" +
	"\x12MarkerDeletedEvent\x12\x1b\n" +
	"\tmarker_id\x18\x01 \x01(\tR\bmarkerId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x1d\n" +
	"\n" +
	"deleted_by\x18\x03 \x01(\tR\tdeletedBy\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xce\x02\n" +
	"\x0fUserJoinedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x17\n" +
	"\agame_id\x18\x03 \x01(\tR\x06gameId\x12=\n" +
	"\x10initial_location\x18\x04 \x01(\v2\x12.realtime.PositionR\x0finitialLocation\x12,\n" +
	"\x06status\x18\x05 \x01(\x0e2\x14.realtime.UserStatusR\x06status\x12C\n" +
	"\bmetadata\x18\x06 \x03(\v2'.realtime.UserJoinedEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Y\n" +
	"\rUserLeftEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xe5\x01\n" +
	"\x17UserLocationUpdateEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12.\n" +
	"\bposition\x18\x03 \x01(\v2\x12.realtime.PositionR\bposition\x12\x18\n" +
	"\aheading\x18\x04 \x01(\x01R\aheading\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x01R\x05speed\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x9c\x01\n" +
	"\x15UserStatusUpdateEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12,\n" +
	"\x06status\x18\x03 \x01(\x0e2\x14.realtime.UserStatusR\x06status\x12#\n" +
	"\rcustom_status\x18\x04 \x01(\tR\fcustomStatus\"\xe4\x01\n" +
	"\x16CollaborationSyncEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x04 \x01(\tR\n" +
	"resourceId\x12\x1c\n" +
	"\toperation\x18\x05 \x01(\tR\toperation\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12\x1a\n" +
	"\brevision\x18\a \x01(\x03R\brevision\"\xdd\x01\n" +
	"\x18CollaborationCursorEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\x12'\n" +
	"\x0fselection_start\x18\x05 \x01(\tR\x0eselectionStart\x12#\n" +
	"\rselection_end\x18\x06 \x01(\tR\fselectionEnd\"E\n" +
	"\tPingEvent\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x88\x01\n" +
	"\tPongEvent\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12A\n" +
	"\x0eping_timestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rpingTimestamp\"v\n" +
	"\n" +
	"ErrorEvent\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\x12 \n" +
	"\vrecoverable\x18\x04 \x01(\bR\vrecoverable\"\xe3\x02\n" +
	"\x0eConnectionInfo\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\agame_id\x18\x03 \x01(\tR\x06gameId\x12=\n" +
	"\fconnected_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\x12\x1b\n" +
	"\tclient_ip\x18\x05 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x06 \x01(\tR\tuserAgent\x12B\n" +
	"\bmetadata\x18\a \x03(\v2&.realtime.ConnectionInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc6\x02\n" +
	"\bRoomInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12'\n" +
	"\x0fconnected_users\x18\x03 \x03(\tR\x0econnectedUsers\x12)\n" +
	"\x10connection_count\x18\x04 \x01(\x05R\x0fconnectionCount\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\bmetadata\x18\x06 \x03(\v2 .realtime.RoomInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xe1\x02\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x1a\n" +
	"\x16CONNECTION_ESTABLISHED\x10\x01\x12\x15\n" +
	"\x11CONNECTION_CLOSED\x10\x02\x12\x12\n" +
	"\x0eMARKER_CREATED\x10\n" +
	"\x12\x12\n" +
	"\x0eMARKER_UPDATED\x10\v\x12\x12\n" +
	"\x0eMARKER_DELETED\x10\f\x12\x16\n" +
	"\x12MARKER_BULK_UPDATE\x10\r\x12\x0f\n" +
	"\vUSER_JOINED\x10\x14\x12\r\n" +
	"\tUSER_LEFT\x10\x15\x12\x18\n" +
	"\x14USER_LOCATION_UPDATE\x10\x16\x12\x16\n" +
	"\x12USER_STATUS_UPDATE\x10\x17\x12\x16\n" +
	"\x12COLLABORATION_SYNC\x10\x1e\x12\x18\n" +
	"\x14COLLABORATION_CURSOR\x10\x1f\x12\x1b\n" +
	"\x17COLLABORATION_SELECTION\x10 \x12\b\n" +
	"\x04PING\x10Z\x12\b\n" +
	"\x04PONG\x10[\x12\t\n" +
	"\x05ERROR\x10c*\\\n" +
	"\n" +
	"UserStatus\x12\x12\n" +
	"\x0eUNKNOWN_STATUS\x10\x00\x12\n" +
	"\n" +
	"\x06ONLINE\x10\x01\x12\b\n" +
	"\x04AWAY\x10\x02\x12\b\n" +
	"\x04BUSY\x10\x03\x12\r\n" +
	"\tINVISIBLE\x10\x04\x12\v\n" +
	"\aOFFLINE\x10\x05B/Z-github.com/ritchermap/realtime/internal/protob\x06proto3"

var (
	file_internal_proto_events_proto_rawDescOnce sync.Once
	file_internal_proto_events_proto_rawDescData []byte
)

func file_internal_proto_events_proto_rawDescGZIP() []byte {
	file_internal_proto_events_proto_rawDescOnce.Do(func() {
		file_internal_proto_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_events_proto_rawDesc), len(file_internal_proto_events_proto_rawDesc)))
	})
	return file_internal_proto_events_proto_rawDescData
}

var file_internal_proto_events_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_proto_events_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_internal_proto_events_proto_goTypes = []any{
	(MessageType)(0),                 // 0: realtime.MessageType
	(UserStatus)(0),                  // 1: realtime.UserStatus
	(*RealtimeMessage)(nil),          // 2: realtime.RealtimeMessage
	(*Position)(nil),                 // 3: realtime.Position
	(*MarkerCreatedEvent)(nil),       // 4: realtime.MarkerCreatedEvent
	(*MarkerUpdatedEvent)(nil),       // 5: realtime.MarkerUpdatedEvent
	(*MarkerDeletedEvent)(nil),       // 6: realtime.MarkerDeletedEvent
	(*UserJoinedEvent)(nil),          // 7: realtime.UserJoinedEvent
	(*UserLeftEvent)(nil),            // 8: realtime.UserLeftEvent
	(*UserLocationUpdateEvent)(nil),  // 9: realtime.UserLocationUpdateEvent
	(*UserStatusUpdateEvent)(nil),    // 10: realtime.UserStatusUpdateEvent
	(*CollaborationSyncEvent)(nil),   // 11: realtime.CollaborationSyncEvent
	(*CollaborationCursorEvent)(nil), // 12: realtime.CollaborationCursorEvent
	(*PingEvent)(nil),                // 13: realtime.PingEvent
	(*PongEvent)(nil),                // 14: realtime.PongEvent
	(*ErrorEvent)(nil),               // 15: realtime.ErrorEvent
	(*ConnectionInfo)(nil),           // 16: realtime.ConnectionInfo
	(*RoomInfo)(nil),                 // 17: realtime.RoomInfo
	nil,                              // 18: realtime.RealtimeMessage.MetadataEntry
	nil,                              // 19: realtime.MarkerCreatedEvent.MetadataEntry
	nil,                              // 20: realtime.MarkerUpdatedEvent.ChangesEntry
	nil,                              // 21: realtime.UserJoinedEvent.MetadataEntry
	nil,                              // 22: realtime.ConnectionInfo.MetadataEntry
	nil,                              // 23: realtime.RoomInfo.MetadataEntry
	(*timestamppb.Timestamp)(nil),    // 24: google.protobuf.Timestamp
}
var file_internal_proto_events_proto_depIdxs = []int32{
	0,  // 0: realtime.RealtimeMessage.type:type_name -> realtime.MessageType
	24, // 1: realtime.RealtimeMessage.timestamp:type_name -> google.protobuf.Timestamp
	18, // 2: realtime.RealtimeMessage.metadata:type_name -> realtime.RealtimeMessage.MetadataEntry
	3,  // 3: realtime.MarkerCreatedEvent.position:type_name -> realtime.Position
	19, // 4: realtime.MarkerCreatedEvent.metadata:type_name -> realtime.MarkerCreatedEvent.MetadataEntry
	3,  // 5: realtime.MarkerUpdatedEvent.old_position:type_name -> realtime.Position
	3,  // 6: realtime.MarkerUpdatedEvent.new_position:type_name -> realtime.Position
	20, // 7: realtime.MarkerUpdatedEvent.changes:type_name -> realtime.MarkerUpdatedEvent.ChangesEntry
	3,  // 8: realtime.UserJoinedEvent.initial_location:type_name -> realtime.Position
	1,  // 9: realtime.UserJoinedEvent.status:type_name -> realtime.UserStatus
	21, // 10: realtime.UserJoinedEvent.metadata:type_name -> realtime.UserJoinedEvent.MetadataEntry
	3,  // 11: realtime.UserLocationUpdateEvent.position:type_name -> realtime.Position
	24, // 12: realtime.UserLocationUpdateEvent.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 13: realtime.UserStatusUpdateEvent.status:type_name -> realtime.UserStatus
	24, // 14: realtime.PingEvent.timestamp:type_name -> google.protobuf.Timestamp
	24, // 15: realtime.PongEvent.timestamp:type_name -> google.protobuf.Timestamp
	24, // 16: realtime.PongEvent.ping_timestamp:type_name -> google.protobuf.Timestamp
	24, // 17: realtime.ConnectionInfo.connected_at:type_name -> google.protobuf.Timestamp
	22, // 18: realtime.ConnectionInfo.metadata:type_name -> realtime.ConnectionInfo.MetadataEntry
	24, // 19: realtime.RoomInfo.created_at:type_name -> google.protobuf.Timestamp
	23, // 20: realtime.RoomInfo.metadata:type_name -> realtime.RoomInfo.MetadataEntry
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_internal_proto_events_proto_init() }
func file_internal_proto_events_proto_init() {
	if File_internal_proto_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_events_proto_rawDesc), len(file_internal_proto_events_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_events_proto_goTypes,
		DependencyIndexes: file_internal_proto_events_proto_depIdxs,
		EnumInfos:         file_internal_proto_events_proto_enumTypes,
		MessageInfos:      file_internal_proto_events_proto_msgTypes,
	}.Build()
	File_internal_proto_events_proto = out.File
	file_internal_proto_events_proto_goTypes = nil
	file_internal_proto_events_proto_depIdxs = nil
}
