spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/ritcher_markers}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      retries: 5
    consumer:
      auto-offset-reset: earliest

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.ritcher.markers: INFO
    org.springframework.security: WARN
    org.hibernate: WARN