# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ritchermap/tiling/v1/tiling.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ritchermap/tiling/v1/tiling.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!ritchermap/tiling/v1/tiling.proto\x12\x14ritchermap.tiling.v1\"\x90\x01\n\x0fTilingRequested\x12\x0e\n\x06map_id\x18\x01 \x01(\x03\x12\x0e\n\x06prefix\x18\x02 \x01(\t\x12\x15\n\rsource_bucket\x18\x03 \x01(\t\x12\x12\n\nsource_key\x18\x04 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x05 \x01(\t\x12\x15\n\x08max_zoom\x18\x06 \x01(\x05H\x00\x88\x01\x01\x42\x0b\n\t_max_zoom\"\x9c\x01\n\x0fTilingCompleted\x12\x0e\n\x06map_id\x18\x01 \x01(\x03\x12\x0e\n\x06prefix\x18\x02 \x01(\t\x12\r\n\x05width\x18\x03 \x01(\x03\x12\x0e\n\x06height\x18\x04 \x01(\x03\x12\x10\n\x08max_zoom\x18\x05 \x01(\x05\x12\x11\n\ttile_size\x18\x06 \x01(\x05\x12\x0e\n\x06\x66ormat\x18\x07 \x01(\t\x12\x15\n\rtiles_written\x18\x08 \x01(\x03\".\n\x0cTilingFailed\x12\x0e\n\x06map_id\x18\x01 \x01(\x03\x12\x0e\n\x06reason\x18\x02 \x01(\tBd\n\x1e\x63om.ritchermap.proto.tiling.v1P\x01Z@github.com/ritchermap/proto/gen/go/ritchermap/tiling/v1;tilingv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ritchermap.tiling.v1.tiling_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.ritchermap.proto.tiling.v1P\001Z@github.com/ritchermap/proto/gen/go/ritchermap/tiling/v1;tilingv1'
  _globals['_TILINGREQUESTED']._serialized_start=60
  _globals['_TILINGREQUESTED']._serialized_end=204
  _globals['_TILINGCOMPLETED']._serialized_start=207
  _globals['_TILINGCOMPLETED']._serialized_end=363
  _globals['_TILINGFAILED']._serialized_start=365
  _globals['_TILINGFAILED']._serialized_end=411
# @@protoc_insertion_point(module_scope)
