global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'map-tile-service'
    static_configs:
      - targets: ['map-tile-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s